# docs: https://kafka.apache.org/documentation/#quickstart_createtopic
version: '3.4'
services:
  kafka:
    hostname: ${HOSTIP-127.0.0.1}
    build: .
    command: ["bash","-c","bin/zookeeper-server-start.sh -daemon config/zookeeper.properties ; while true ;do curl 127.0.0.1:2181 2>&1 |grep 'Empty reply from server' && break ; sleep 1 ;done ; bin/kafka-server-start.sh config/server.properties "]
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
