# docs: https://kafka.apache.org/documentation/#quickstart_createtopic
version: '2'
services:
  kafka:
    hostname: ${HOSTIP}
    build: .
    command: ["bash","-c","bin/zookeeper-server-start.sh -daemon config/zookeeper.properties && bin/kafka-server-start.sh config/server.properties "]
    ports:
      - "9092:9092"
      - "2181:2181"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
